id: I6EC1C219
legacy_id: P004598
ocr_import_info:
  bdrc_scan_id: W1KG3710
  source: bdrc
  ocr_info:
    timestamp: '2020-03-30T21:24:16'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T15:14:10.137294+00:00'
last_modified: 2022-08-31 23:14:26.147192
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG3710
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG3710
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དགའ་ལྡན་ཕྱག་རྒྱ་ཆེན་པོ་དང་ཟབ་ལམ་བླ་མའི་རྣལ་འབྱོར་བཟུང་འབྲེལ་གྱི་ཟིན་བྲིས་སྙན་རྒྱུད་མན་ངག་ཟབ་གསལ།
  author: བསྟན་འཛིན་རབ་རྒྱས།
statistics:
  ocr_word_mean_confidence_index: 0.843810584346617
  ocr_word_median_confidence_index: 0.9300000071525574
quality: null
bases:
  I1KG3795:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG3795
      total_pages: 674
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG3795.txt
    statistics:
      ocr_word_median_confidence_index: 0.9300000071525574
      ocr_word_mean_confidence_index: 0.843810584346617
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
